import category from '@/app/category/page';

export const productsData = [
  {
    name: 'Black Panther Bobblehead | Avengers',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-black-panther/1000114762.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-black-panther/1000114764.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-black-panther/1000114766.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-black-panther/1000114768.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: 'b107fe68-15cd-4139-aae4-027465f895df',
    series: 'Avengers',
    category: 'Bobble head',
  },
  {
    name: 'Captain America Bobblehead | Avengers',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-captain-america/1000114961.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-captain-america/1000114963.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-captain-america/1000114966.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '161a5ca3-9fee-4f90-8759-1095db9e8d53',
    series: 'Avengers',
    category: 'Bobble head',
  },
  {
    name: 'Captain America Bobblehead | Avengers',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-caption-america/1000114754.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-caption-america/1000114756.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-caption-america/1000114758.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-caption-america/1000114760.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '5876fa45-70bf-44e6-a455-da7e51f2bc8e',
    series: 'Avengers',
    category: 'Bobble head',
  },
  {
    name: 'DeadPool Bobblehead | Avengers',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-dead-pool/1000114873.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-dead-pool/1000114877.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-dead-pool/1000114877.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '7cb45764-a22b-49a8-b9a9-6ca3e677304f',
    series: 'Avengers',
    category: 'Bobble head',
  },
  {
    name: 'Dr. Strange Bobblehead | Avengers',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-dr-strange/1000114773.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-dr-strange/1000114775.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-dr-strange/1000114777.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-dr-strange/1000114779.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '0d036079-48f0-4c68-9fd1-d78c91f5dabd',
    series: 'Avengers',
    category: 'Bobble head',
  },
  {
    name: 'Gaara Bobblehead | Naruto',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-gaara-naruto/1000114873.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-gaara-naruto/1000114875.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-gaara-naruto/1000114877.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-gaara-naruto/1000114879.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '945b3093-0505-48ed-999f-cdb3c4dc6d75',
    series: 'Naruto',
    category: 'Bobble head',
  },
  {
    name: 'Gojo Bobblehead | Jujutsu Kaisen',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-gojo/1000114781.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-gojo/1000114783.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-gojo/1000114785.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-gojo/1000114787.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '8336fa39-0a07-4d51-9c5b-7065318fa409',
    series: 'Jujutsu Kaisen',
    category: 'Bobble head',
  },
  {
    name: 'Groot Bobblehead | Avengers',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-groot/1000114773.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-groot/1000114775.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-groot/1000114777.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-groot/1000114779.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '8bcb6c27-651f-4db7-b1b1-7af521109c9a',
    series: 'Avengers',
    category: 'Bobble head',
  },
  {
    name: 'Harry Potter Bobblehead | Harry Potter',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-harry-pooter/1000114847.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-harry-pooter/1000114847.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-harry-pooter/1000114847.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-harry-pooter/1000114847.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: 'e6f8423d-65e7-4ec8-a6be-69edf83d6933',
    series: 'Harry Potter',
    category: 'Bobble head',
  },
  {
    name: 'Itachi Uchiha Bobblehead | Naruto',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-itachi/1000114754.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-itachi/1000114756.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-itachi/1000114758.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-itachi/1000114760.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: 'c49fac91-4379-4602-86a5-87527ef5634d',
    series: 'Naruto',
    category: 'Bobble head',
  },
  {
    name: 'Jerry Bobblehead | Tom&Jerry',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-jarry/1000114847.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-jarry/1000114849.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-jarry/1000114851.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-jarry/1000114853.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '2f15cb2e-ce40-45ad-9fe7-d35b6117c9c7',
    series: 'Tom&Jerry',
    category: 'Bobble head',
  },
  {
    name: 'Kakashi Bobblehead | Naruto',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-kakashi/1000114855.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-kakashi/1000114857.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-kakashi/1000114859.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-kakashi/1000114861.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '18704679-fa01-4313-9a6d-9c4151d30e8b',
    series: 'Naruto',
    category: 'Bobble head',
  },
  {
    name: 'Kimetchu Bobblehead | Demon slayer',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-kimetchu/1000114839.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-kimetchu/1000114841.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-kimetchu/1000114843.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-kimetchu/1000114845.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '8165b5f7-1ff4-45c2-88d1-c6f90c6e0cce',
    series: 'Demon slayer',
    category: 'Bobble head',
  },
  {
    name: 'Lufi Bobblehead | One Piece',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-lufi/1000114789.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-lufi/1000114791.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-lufi/1000114793.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-lufi/1000114795.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '645b5727-8c74-4a68-a449-632d0c447f1b',
    series: 'One Piece',
    category: 'Bobble head',
  },
  {
    name: 'Naruto Bobblehead | Naruto',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-naruto/1000114864.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-naruto/1000114866.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-naruto/1000114868.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-naruto/1000114870.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: 'cff40ecf-6687-488e-ad28-0d8b2b6d1925',
    series: 'Naruto',
    category: 'Bobble head',
  },
  {
    name: 'Neymar Bobblehead | Neymar',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-neymar/1000114773.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-neymar/1000114775.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-neymar/1000114777.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-neymar/1000114779.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: 'ac52cd78-a08e-457a-89d0-07192780729c',
    series: 'Neymar',
    category: 'Bobble head',
  },
  {
    name: 'Pikachu Bobblehead | Pikachu',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-pikachu/1000114781.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-pikachu/1000114783.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-pikachu/1000114785.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-pikachu/1000114787.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: 'a891b404-c63d-4374-acf7-4e14da912821',
    series: 'Pikachu',
    category: 'Bobble head',
  },
  {
    name: 'Saskey Bobblehead | Naruto',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-saskey/1000114762.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-saskey/1000114764.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-saskey/1000114766.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-saskey/1000114768.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '228f0d49-83eb-4dff-9bad-a0631d207ccf',
    series: 'Naruto',
    category: 'Bobble head',
  },
  {
    name: 'Spider Man Bobblehead | Avenger',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-spider-man/1000114781.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-spider-man/1000114783.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-spider-man/1000114785.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-spider-man/1000114787.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '8c42e948-d4a4-4cf9-add0-d947d204538c',
    series: 'Avenger',
    category: 'Bobble head',
  },
  {
    name: 'Mubco Bobblehead | Star Wars',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-start-war/1000114762.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-start-war/1000114764.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-start-war/1000114766.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-start-war/1000114768.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '721a92f7-3929-42ec-a5a9-67139e3f07f3',
    series: 'Star Wars',
    category: 'Bobble head',
  },
  {
    name: 'Tanjiro Bobblehead | Demon slayer',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-tanjiro/1000114789.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-tanjiro/1000114791.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-tanjiro/1000114793.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-tanjiro/1000114795.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: 'c02fd3a9-b705-4433-bcb5-82cf0b8a23de',
    series: 'Demon slayer',
    category: 'Bobble head',
  },
  {
    name: 'Thanos Bobblehead | Avenger',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-thanos/1000114754.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-thanos/1000114756.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-thanos/1000114758.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-thanos/1000114760.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '007c567a-b63d-4d55-8950-2d3b22c9cc71',
    series: 'Avenger',
    category: 'Bobble head',
  },
  {
    name: 'Tom Bobblehead | Tom&Jarry',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-tom/1000114855.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-tom/1000114857.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-tom/1000114859.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-tom/1000114861.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '3638ccab-045a-4ccd-9fe0-232f11489adc',
    series: 'Tom&Jarry',
    category: 'Bobble head',
  },
  {
    name: 'Zoro Bobblehead | One Piece',
    images: [
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-zoro/1000114839.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-zoro/1000114841.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-zoro/1000114843.png',
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/booble-zoro/1000114845.png',
    ],
    price: 460,
    discountPrice: 279,
    description: `your favorite characters, these bobbleheads are the perfect action figures. It's the superhero/action hero Bobble Head for your car/home/office desk, Needless to say, this quirky bobblehead is made for the die-hard fans of the action heroes. If you're looking for Superhero Collectibles or a gift for a Superhero fan, you've come to the right place!`,
    productHeadlines: ['Mobile holder', 'Car dashboard', 'Office desk'],
    id: '6472577a-3d37-495f-9fa4-8b78f7c70cd8',
    series: 'One Piece',
    category: 'Bobble head',
  },
];

export const categoryData = [
  {
    name: 'Action figure',
    description: 'High-quality figures',
    image:
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/category/Black+Modern+Bag+Product+Amazon+Product+Image+(4).png',
    slug: '/category/action-figure',
  },
  {
    name: 'Miniature',
    description: 'High-quality figures',
    image: 'https://s3.ap-south-1.amazonaws.com/cozzy.corner/category/10.png',
    slug: '/category/miniature',
  },
  {
    name: 'Bobble head',
    description: 'High-quality figures',
    image: 'https://s3.ap-south-1.amazonaws.com/cozzy.corner/category/8.png',
    slug: '/category/bobble-head',
  },
  {
    name: 'Sets',
    description: 'High-quality figures',
    image: 'https://s3.ap-south-1.amazonaws.com/cozzy.corner/category/13.png',
    slug: '/category/sets',
  },
];

export const seriesCategoryData = [
  {
    name: 'Naruto',
    description: 'High-quality figures',
    image:
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/category/Black+Modern+Bag+Product+Amazon+Product+Image+(4).png',
    slug: '/series/naruto',
  },
  {
    name: 'One piece',
    description: 'High-quality figures',
    image: 'https://s3.ap-south-1.amazonaws.com/cozzy.corner/category/10.png',
    slug: '/series/one-piece',
  },
  {
    name: 'Demon slayer',
    description: 'High-quality figures',
    image: 'https://s3.ap-south-1.amazonaws.com/cozzy.corner/category/8.png',
    slug: '/series/demon-slayer',
  },
  {
    name: 'Dragon Ball',
    description: 'High-quality figures',
    image: 'https://s3.ap-south-1.amazonaws.com/cozzy.corner/category/13.png',
    slug: '/series/dragon-ball',
  },
  {
    name: 'Others',
    description: 'High-quality figures',
    image: 'https://s3.ap-south-1.amazonaws.com/cozzy.corner/category/13.png',
    slug: '/series/others',
  },
];

export const instagramGallaryData = [
  {
    image:
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/instagram/WhatsApp+Image+2024-10-18+at+14.57.28_98b5e38b.jpg',
    link: 'https://www.instagram.com/p/CmXzVJ6Kv2i/',
  },
  {
    image:
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/instagram/WhatsApp+Image+2024-10-18+at+14.57.28_5aad02fa.jpg',
    link: 'https://www.instagram.com/p/CmXzVJ6Kv2i/',
  },
  {
    image:
      'https://s3.ap-south-1.amazonaws.com/cozzy.corner/instagram/WhatsApp+Image+2024-10-18+at+14.57.28_e04d7f56.jpg',
    link: 'https://www.instagram.com/p/CmXzVJ6Kv2i/',
  },
];
